[package]
name = "dumb-init"
version = "0.1.0"
authors = ["Thomas Wickham <thomas@wickham.epimeros.org>"]

[dependencies]
libc = "0.2"
clap = "2.2"
fern = "0.3"
log  = "0.3"
time = "0.1"
lazy_static = "0.1"
